'use client';

//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider, useQuery } from 'react-query'
import Head from "next/head";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Weather",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const queryClient = new QueryClient();

  return (
    <html lang="ko">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  );
}

// src 폴더 옆에 .env.local 파일 만들어서 설정값 저장해놓기

// TanStack Query (React Query) : 
// npm install react-query

// useEffect(() => {
//   document.title = "Weather"; // 페이지 제목 설정
//   const metaDescription = document.createElement('meta');
//   metaDescription.name = 'description';
//   metaDescription.content = 'Generated by create next app';
//   document.head.appendChild(metaDescription); // 메타 설명 설정

//   return () => {
//     document.head.removeChild(metaDescription); // 컴포넌트 언마운트 시 메타 설명 제거
//   };
// }, []);